name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new feature! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What problem does this feature solve? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this feature?
      options:
        - priority:low
        - priority:medium
        - priority:high
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How large is this feature?
      options:
        - size:xs (few hours)
        - size:s (1-2 days)
        - size:m (3-5 days)
        - size:l (1-2 weeks)
        - size:xl (2+ weeks)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Tests added/updated
        - [ ] Documentation updated
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contribution guidelines
      options:
        - label: I have checked for duplicate issues
          required: true
        - label: I have provided all the necessary information
          required: true