gitGraph
    commit id: "Initial"
    branch develop
    checkout develop
    commit id: "Dev Start"

    branch feature/xyz
    checkout feature/xyz
    commit id: "Feature Work"
    checkout develop
    merge feature/xyz id: "Feature PR to develop" type: HIGHLIGHT tag: "QA Review"

    branch bugfix/abc
    checkout bugfix/abc
    commit id: "Bug Fix"
    checkout develop
    merge bugfix/abc id: "Bugfix PR to develop" type: HIGHLIGHT tag: "QA Review"

    branch rc
    checkout rc
    commit id: "RC Start"
    checkout develop
    merge rc id: "PR to RC" type: HIGHLIGHT tag: "QA Review"

    branch hotfix/def
    checkout hotfix/def
    commit id: "Hot Fix"
    checkout main
    merge hotfix/def id: "Hotfix PR to main" type: HIGHLIGHT tag: "Customer Review"

    merge rc id: "Release" type: HIGHLIGHT tag: "Customer Review"